# Generated by Django 4.2.2 on 2024-04-09 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('Cat_name', models.CharField(max_length=150)),
                ('Cat_image', models.ImageField(blank=True, null=True, upload_to='images/product')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('ProdTitle', models.CharField(max_length=100)),
                ('ProdName', models.CharField(default='', max_length=150)),
                ('product_imageMain', models.ImageField(default='', upload_to='images/product')),
                ('product_image2', models.ImageField(default='', upload_to='images/product')),
                ('product_image3', models.ImageField(default='', upload_to='images/product')),
                ('product_image4', models.ImageField(default='', upload_to='images/product')),
                ('product_image5', models.ImageField(default='', upload_to='images/product')),
                ('selling_price', models.FloatField()),
                ('original_price', models.FloatField()),
                ('Prod_Desc', models.TextField()),
                ('quantity', models.IntegerField()),
                ('off_On_Product', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.BooleanField(default=False, help_text='0=default, 1=Hidden')),
                ('trending', models.BooleanField(default=False, help_text='0=default, 1=Trending')),
                ('tag', models.CharField(blank=True, max_length=150, null=True)),
                ('Key_Feature', models.CharField(blank=True, max_length=1000, null=True)),
                ('Unit', models.CharField(blank=True, max_length=150, null=True)),
                ('Net_Weight', models.CharField(blank=True, max_length=100, null=True)),
                ('Shelf_Life', models.CharField(blank=True, max_length=150, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('meta_Keywords', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
